language: node_js
node_js:
  - "12"

before_install:
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: www
  target_branch: master
  fqdn: nick.winans.codes
  on:
    branch: dev
