/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface BrowserPreview {}
  interface BrowserPreviewAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'BrowserPreview': Components.BrowserPreview;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'browser-preview': Components.BrowserPreviewAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLBrowserPreviewElement extends Components.BrowserPreview, HTMLStencilElement {}
  var HTMLBrowserPreviewElement: {
    prototype: HTMLBrowserPreviewElement;
    new (): HTMLBrowserPreviewElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'browser-preview': HTMLBrowserPreviewElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'browser-preview': HTMLBrowserPreviewElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
