/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  project,
  skillSet,
} from './common/types';
import {
  IconLookup,
  IconName,
} from '@fortawesome/fontawesome-svg-core';


export namespace Components {

  interface AboutSection {}
  interface AboutSectionAttributes extends StencilHTMLAttributes {}

  interface AppFooter {}
  interface AppFooterAttributes extends StencilHTMLAttributes {}

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppImg {
    'alt': string;
    'src': string;
    'type': 'jpg' | 'png';
  }
  interface AppImgAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'src'?: string;
    'type'?: 'jpg' | 'png';
  }

  interface AppProject {
    'config': project;
  }
  interface AppProjectAttributes extends StencilHTMLAttributes {
    'config'?: project;
  }

  interface AppSection {}
  interface AppSectionAttributes extends StencilHTMLAttributes {}

  interface BrowserPreview {
    'direction': 'left' | 'right';
    'site': string;
  }
  interface BrowserPreviewAttributes extends StencilHTMLAttributes {
    'direction'?: 'left' | 'right';
    'site'?: string;
  }

  interface FontawesomeIcon {
    'class'?: string;
    'icon': IconLookup | IconName;
  }
  interface FontawesomeIconAttributes extends StencilHTMLAttributes {
    'class'?: string;
    'icon'?: IconLookup | IconName;
  }

  interface SkillPanel {
    'config': skillSet;
  }
  interface SkillPanelAttributes extends StencilHTMLAttributes {
    'config'?: skillSet;
  }

  interface SkillsSection {
    'skills': skillSet[];
  }
  interface SkillsSectionAttributes extends StencilHTMLAttributes {
    'skills'?: skillSet[];
  }
}

declare global {
  interface StencilElementInterfaces {
    'AboutSection': Components.AboutSection;
    'AppFooter': Components.AppFooter;
    'AppHome': Components.AppHome;
    'AppImg': Components.AppImg;
    'AppProject': Components.AppProject;
    'AppSection': Components.AppSection;
    'BrowserPreview': Components.BrowserPreview;
    'FontawesomeIcon': Components.FontawesomeIcon;
    'SkillPanel': Components.SkillPanel;
    'SkillsSection': Components.SkillsSection;
  }

  interface StencilIntrinsicElements {
    'about-section': Components.AboutSectionAttributes;
    'app-footer': Components.AppFooterAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-img': Components.AppImgAttributes;
    'app-project': Components.AppProjectAttributes;
    'app-section': Components.AppSectionAttributes;
    'browser-preview': Components.BrowserPreviewAttributes;
    'fontawesome-icon': Components.FontawesomeIconAttributes;
    'skill-panel': Components.SkillPanelAttributes;
    'skills-section': Components.SkillsSectionAttributes;
  }


  interface HTMLAboutSectionElement extends Components.AboutSection, HTMLStencilElement {}
  var HTMLAboutSectionElement: {
    prototype: HTMLAboutSectionElement;
    new (): HTMLAboutSectionElement;
  };

  interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {}
  var HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppImgElement extends Components.AppImg, HTMLStencilElement {}
  var HTMLAppImgElement: {
    prototype: HTMLAppImgElement;
    new (): HTMLAppImgElement;
  };

  interface HTMLAppProjectElement extends Components.AppProject, HTMLStencilElement {}
  var HTMLAppProjectElement: {
    prototype: HTMLAppProjectElement;
    new (): HTMLAppProjectElement;
  };

  interface HTMLAppSectionElement extends Components.AppSection, HTMLStencilElement {}
  var HTMLAppSectionElement: {
    prototype: HTMLAppSectionElement;
    new (): HTMLAppSectionElement;
  };

  interface HTMLBrowserPreviewElement extends Components.BrowserPreview, HTMLStencilElement {}
  var HTMLBrowserPreviewElement: {
    prototype: HTMLBrowserPreviewElement;
    new (): HTMLBrowserPreviewElement;
  };

  interface HTMLFontawesomeIconElement extends Components.FontawesomeIcon, HTMLStencilElement {}
  var HTMLFontawesomeIconElement: {
    prototype: HTMLFontawesomeIconElement;
    new (): HTMLFontawesomeIconElement;
  };

  interface HTMLSkillPanelElement extends Components.SkillPanel, HTMLStencilElement {}
  var HTMLSkillPanelElement: {
    prototype: HTMLSkillPanelElement;
    new (): HTMLSkillPanelElement;
  };

  interface HTMLSkillsSectionElement extends Components.SkillsSection, HTMLStencilElement {}
  var HTMLSkillsSectionElement: {
    prototype: HTMLSkillsSectionElement;
    new (): HTMLSkillsSectionElement;
  };

  interface HTMLElementTagNameMap {
    'about-section': HTMLAboutSectionElement
    'app-footer': HTMLAppFooterElement
    'app-home': HTMLAppHomeElement
    'app-img': HTMLAppImgElement
    'app-project': HTMLAppProjectElement
    'app-section': HTMLAppSectionElement
    'browser-preview': HTMLBrowserPreviewElement
    'fontawesome-icon': HTMLFontawesomeIconElement
    'skill-panel': HTMLSkillPanelElement
    'skills-section': HTMLSkillsSectionElement
  }

  interface ElementTagNameMap {
    'about-section': HTMLAboutSectionElement;
    'app-footer': HTMLAppFooterElement;
    'app-home': HTMLAppHomeElement;
    'app-img': HTMLAppImgElement;
    'app-project': HTMLAppProjectElement;
    'app-section': HTMLAppSectionElement;
    'browser-preview': HTMLBrowserPreviewElement;
    'fontawesome-icon': HTMLFontawesomeIconElement;
    'skill-panel': HTMLSkillPanelElement;
    'skills-section': HTMLSkillsSectionElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
